### ISSUE TITLE
How to write search options in web applications

### ISSUE THREAD

**Issue by ghost** [MarkLogicUniversity/top-songs#4]
Hi,
I am trying to write search options in one of the spring controller classes but it is giving me 
'RESTAPI-EMPTYBODY (err:FOER0000): Empty POST or PUT body'

```
                    String optionXml = <search:options xmlns:search='http://marklogic.com/appservices     /search'>
```

 <search:values name='country'>
search:values-optionfrequency-order/search:values-option
search:values-optionlimit=5/search:values-option
<search:range collation='http://marklogic.com/collation/' type='xs:string'>
<search:element ns='' name='country'/>
/search:range
/search:values
/search:options;

```
    // create a handle to send the query options
    StringHandle writeHandle = new StringHandle();
    //StringHandle writeHandle = new StringHandle();
    writeHandle.withFormat(Format.XML).set(optionXml);
    // write the query options to the database
    optionsMgr.writeOptions("myOptions", writeHandle);
```

But this line of code is giving exception :optionsMgr.writeOptions("myOptions", writeHandle);
Is there a way to fix this problem.

**Comment by gregnist** [comment]
I have found it easier to just build your desired search options documents outside of the Java API code using a text editor.  Then once you have built the XML document, load it into your modules databases using a load method of your choice.

**Comment by ghost** [comment]
Hi Gregnist,
I tried loading it with Bulk load using admin but it is giving some error -
Load Failed : XDMP-DOCSTARTTAGCHAR: Unexpected character "&quot;" in start tag at C:\Users\comp\Desktop\module\search-options.xml line 1

Can you please share one working search options xml file so that I can re-configure it and use it.

![search-options](https://cloud.githubusercontent.com/assets/3964763/6351487/0c473fb8-bc62-11e4-9009-0ac76a63e09c.png)

**Comment by joecrean** [comment]
Hi there are options files in the git project. There is also a sample load client under the Java package ending with admin.

Sent from mobile device, fat finger disclaimer active

On 24.02.2015, at 15:46, niranjanMaisnam <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Gregnist,
I tried loading it with Bulk load using admin but it is giving some error -
Load Failed : XDMP-DOCSTARTTAGCHAR: Unexpected character """ in start tag at C:\Users\comp\Desktop\module\search-options.xml line 1

Can you please share one working search options xml file so that I can re-configure it and use it.

[search-options]https://cloud.githubusercontent.com/assets/3964763/6351487/0c473fb8-bc62-11e4-9009-0ac76a63e09c.png

**Comment by gregnist** [comment]
Yep, specifically you can find the search options here:

https://github.com/marklogic/top-songs/tree/master/java/TopSongs/src/data

For the full options for the top songs project please reference "query-options-full.xml".

**Comment by ghost** [comment]
Thanks gregnist, but is there a way out to do it from java spring controller class itself , I find loading xml before the application starts a bit cumbersome. Please let me know

**Comment by ghost** [comment]
Thanks gregnist and joecrean, I have learnt a lot from your TopSongs and thanks for sharing this project on github .
